"""Common utilities: tolerant JSON extraction, translatability checks, safe filenames."""
import re
import uuid

from .config import ALLOWED_EXTENSIONS

# The api layer references this as utils.SUPPORTED_EXTENSIONS (explicit re-export; do not remove)
SUPPORTED_EXTENSIONS = ALLOWED_EXTENSIONS

_XOR_KEY = b"doc-translator-local-obfuscation"


def new_task_id() -> str:
    """Task ID generated by the service; also used in path concatenation
    (to prevent path traversal)."""
    return uuid.uuid4().hex


def valid_task_id(task_id: str) -> bool:
    return bool(re.fullmatch(r"[0-9a-f]{32}", task_id or ""))


def obfuscate_secret(raw: str) -> str:
    data = bytes(raw.encode("utf-8"))
    return (bytes(b ^ _XOR_KEY[i % len(_XOR_KEY)] for i, b in enumerate(data))).hex()


def deobfuscate_secret(enc: str) -> str:
    if not enc:
        return ""
    try:
        data = bytes.fromhex(enc)
        return bytes(b ^ _XOR_KEY[i % len(_XOR_KEY)] for i, b in enumerate(data)).decode("utf-8")
    except (ValueError, UnicodeDecodeError):
        return ""


def extract_json_object(text: str) -> dict | None:
    """Best-effort extraction of one JSON object from an LLM response.

    Handles: markdown fences, surrounding prose, trailing commas.
    Returns None if the response cannot be parsed at all.
    """
    if not text:
        return None
    text = text.strip()
    # Strip ``` fences
    fence = re.search(r"```(?:json)?\s*(.*?)\s*```", text, re.DOTALL)
    if fence:
        text = fence.group(1).strip()
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end <= start:
        return None
    body = text[start:end + 1]
    for candidate in (body, re.sub(r",\s*([}\]])", r"\1", body)):
        try:
            obj = __import__("json").loads(candidate)
            if isinstance(obj, dict):
                return obj
        except Exception:
            continue
    return None


_URL_RE = re.compile(r"(https?://\S+|www\.\S+|[\w.+-]+@[\w-]+\.[\w.-]+)")


def is_translatable(text: str) -> tuple[bool, str]:
    """Returns (is_translatable, skip_reason). Only does structural filtering;
    language detection is left to the caller."""
    t = (text or "").strip()
    if len(t) < 2:
        return False, "too_short"
    stripped = _URL_RE.sub("", t)
    stripped = re.sub(r"[\s\d\W]", "", stripped)  # strip whitespace/digits/punctuation (including full-width)
    if not stripped:
        return False, "no_text"
    # Looks like code: dense underscores/braces, or long camelcase without spaces
    if len(t) >= 8:
        symbol_ratio = sum(c in "_{}<>=/" for c in t) / len(t)
        has_space = " " in t.strip()
        camel = re.search(r"[a-z][A-Z][a-zA-Z]*[a-zA-Z]", t.replace(" ", ""))
        if not has_space and (symbol_ratio > 0.15 or (camel and len(t) > 20)):
            return False, "looks_like_code"
    return True, ""


def sanitize_filename(name: str) -> str:
    name = re.sub(r'[\\/:*?"<>|\r\n]', "_", name or "").strip()
    return name[:120] or "file"


def content_disposition(filename: str) -> str:
    """RFC 5987 encoding; supports non-ASCII filenames."""
    from urllib.parse import quote
    ascii_name = filename.encode("ascii", "ignore").decode() or "download"
    ascii_name = ascii_name.replace('"', "")
    return f'attachment; filename="{ascii_name}"; filename*=UTF-8\'\'{quote(filename)}'
